using Dapper;
using Npgsql;
using System;
using System.Collections.Generic;
using System.Text;

namespace DataHarvester.DBHelpers
{
	public static class StudyTableBuildersAD
	{
		public static void create_table_studies(string db_conn)
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.studies(
                ad_id                  INT    GENERATED BY DEFAULT AS IDENTITY (START WITH 2000001) PRIMARY KEY   
			  , sd_id                  VARCHAR         PRIMARY KEY
              , hash_id                CHAR(32)        NULL
			  , display_title          VARCHAR         NULL
              , title_lang_code        VARCHAR         NULL default 'en'
			  , brief_description      VARCHAR         NULL
              , bd_contains_html       BOOLEAN         NULL	default false
			  , data_sharing_statement VARCHAR         NULL
              , dss_contains_html      BOOLEAN         NULL	default false
			  , study_start_year       INT             NULL
			  , study_start_month      INT             NULL
			  , study_type_id          INT             NULL
			  , study_status_id        INT             NULL
			  , study_enrolment        INT             NULL
			  , study_gender_elig_id   INT             NULL
			  , min_age                INT             NULL
			  , min_age_units_id       INT             NULL
			  , max_age                INT             NULL
			  , max_age_units_id       INT             NULL
			  , datetime_of_data_fetch TIMESTAMPTZ     NULL
              , record_hash            CHAR(32)        NULL
              , study_full_hash        CHAR(32)        NULL
			);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public static void create_table_study_identifiers(string db_conn)
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.study_identifiers(
			    sd_id                  VARCHAR         NOT NULL
              , study_hash_id          CHAR(32)        NULL
			  , identifier_value       VARCHAR         NULL
			  , identifier_type_id     INT             NULL
			  , identifier_org_id      INT             NULL
			  , identifier_org         VARCHAR         NULL
			  , identifier_date        VARCHAR         NULL
			  , identifier_link        VARCHAR         NULL
              , record_hash            CHAR(32)        NULL
			);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public static void create_table_study_relationships(string db_conn)
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.study_relationships(
			    sd_id                  VARCHAR         NOT NULL
              , study_hash_id          CHAR(32)        NULL
			  , relationship_type_id   INT             NULL
			  , relationship_type      VARCHAR         NULL
			  , target_sd_id           VARCHAR         NULL
              , record_hash            CHAR(32)        NULL
			);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public static void create_table_study_references(string db_conn)
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.study_references(
				sd_id                  VARCHAR         NOT NULL
              , study_hash_id          CHAR(32)        NULL
			  , pmid                   VARCHAR         NULL
			  , citation               VARCHAR         NULL
			  , doi                    VARCHAR         NULL	
			  , comments               VARCHAR         NULL
              , record_hash            CHAR(32)        NULL
			);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public static void create_table_study_titles(string db_conn)
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.study_titles(
				sd_id                  VARCHAR         NOT NULL
              , study_hash_id          CHAR(32)        NULL
			  , title_text             VARCHAR         NULL
			  , title_type_id          INT             NULL
			  , title_lang_code        VARCHAR         NOT NULL default 'en'
			  , lang_usage_id          INT             NOT NULL default 11
			  , is_default             BOOLEAN         NULL
			  , comments               VARCHAR         NULL
			  , comparison_text        VARCHAR         NULL
              , record_hash            CHAR(32)        NULL
			);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public static void create_table_study_hashes(string db_conn)
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.study_hashes(
				sd_id                  VARCHAR         NOT NULL
			  , study_hash_id          CHAR(32)        NULL
			  , hash_type_id           INT             NULL
			  , composite_hash         CHAR(32)        NULL
			);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}
	}


	public static class ObjectTableBuildersAD
	{
		public static void create_table_data_objects(string db_conn)
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.data_objects(
				sd_id                  VARCHAR         NOT NULL
			  , do_id                  INT             NOT NULL
              , hash_id                CHAR(32)        NULL
              , study_hash_id          CHAR(32)        NULL
			  , display_title          VARCHAR         NULL
			  , doi                    VARCHAR         NULL 
			  , doi_status_id          INT             NULL
			  , publication_year       INT             NULL
			  , object_class_id        INT             NULL
			  , object_type_id         INT             NULL
			  , managing_org_id        INT             NULL
			  , managing_org           VARCHAR         NULL
			  , access_type_id         INT             NULL
			  , access_details         VARCHAR         NULL
			  , access_details_url     VARCHAR         NULL
			  , url_last_checked       DATE            NULL
			  , add_study_contribs     BOOLEAN         NULL
			  , add_study_topics       BOOLEAN         NULL
			  , datetime_of_data_fetch TIMESTAMPTZ     NULL
              , record_hash            CHAR(32)        NULL
              , object_full_hash       CHAR(32)        NULL
			);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public static void create_table_dataset_properties(string db_conn)
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.dataset_properties(
				sd_id                  VARCHAR         NOT NULL
			  , do_id                  INT             NOT NULL
              , study_hash_id          CHAR(32)        NULL
              , object_hash_id         CHAR(32)        NULL
			  , record_keys_type_id    INT             NULL 
			  , record_keys_details    VARCHAR         NULL    
			  , identifiers_type_id    INT             NULL  
			  , identifiers_details    VARCHAR         NULL    
			  , consents_type_id       INT             NULL  
              , consents_details       VARCHAR         NULL 
              , record_hash            CHAR(32)        NULL
			);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public static void create_table_object_dates(string db_conn)
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.object_dates(
				sd_id                  VARCHAR         NOT NULL
			  , do_id                  INT             NOT NULL
              , study_hash_id          CHAR(32)        NULL
              , object_hash_id         CHAR(32)        NULL
			  , date_type_id           INT             NULL
			  , is_date_range          BOOLEAN         NULL default false
			  , date_as_string         VARCHAR         NULL
			  , start_year             INT             NULL
			  , start_month            INT             NULL
			  , start_day              INT             NULL
			  , end_year               INT             NULL
			  , end_month              INT             NULL
			  , end_day                INT             NULL
			  , details                VARCHAR         NULL
              , record_hash            CHAR(32)        NULL
			);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public static void create_table_object_instances(string db_conn)
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.object_instances(
				sd_id                  VARCHAR         NOT NULL
			  , do_id                  INT             NOT NULL
              , study_hash_id          CHAR(32)        NULL
              , object_hash_id         CHAR(32)        NULL
			  , instance_type_id       INT             NOT NULL  default 1
			  , repository_org_id      INT             NULL
			  , repository_org         VARCHAR         NULL
			  , url                    VARCHAR         NULL
			  , url_accessible         BOOLEAN         NULL
			  , url_last_checked       DATE            NULL
			  , resource_type_id       INT             NULL
			  , resource_size          VARCHAR         NULL
			  , resource_size_units    VARCHAR         NULL
              , record_hash            CHAR(32)        NULL
			);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public static void create_table_object_titles(string db_conn)
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.object_titles(
				sd_id                  VARCHAR         NOT NULL
			  , do_id                  INT             NOT NULL
              , study_hash_id          CHAR(32)        NULL
              , object_hash_id         CHAR(32)        NULL
			  , title_text             VARCHAR         NULL
			  , title_type_id          INT             NULL
			  , title_lang_code        VARCHAR         NOT NULL default 'en'
			  , lang_usage_id          INT             NOT NULL default 11
			  , is_default             BOOLEAN         NULL
			  , comments               VARCHAR         NULL
			  , comparison_text        VARCHAR         NULL
              , record_hash            CHAR(32)        NULL
			);";

			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}


		public static void create_table_object_hashes(string db_conn)
		{
			string sql_string = @"CREATE TABLE IF NOT EXISTS ad.object_hashes(
				sd_id                  VARCHAR         NOT NULL
              , do_id                  INT             NULL
			  , study_hash_id          CHAR(32)        NULL
              , object_hash_id         CHAR(32)        NULL
			  , hash_type_id           INT             NULL
              , composite_hash         CHAR(32)        NULL
			);";


			using (var conn = new NpgsqlConnection(db_conn))
			{
				conn.Execute(sql_string);
			}
		}
	}
}

